apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy
spec:
  inputs:
    params:
      - name: dc-name
        description: DeploymentConfig name to deploy
  steps:
    - name: deploy
      image: quay.io/openshiftlabs/openshift-cli-tekton-workshop:2.0
      command: ["/usr/local/bin/oc"]
      args:
        - "rollout latest $(inputs.params.dc-name)"
